/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RecommendRouteImport } from './routes/recommend'
import { Route as StartRouteImport } from './routes/start'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as BuilderProjectIdRouteImport } from './routes/builder.$projectId'
import { Route as LegalIndexRouteImport } from './routes/legal.index'
import { Route as LegalDocRouteImport } from './routes/legal.$doc'
import { Route as PreviewProjectIdRouteImport } from './routes/preview.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendRoute = RecommendRouteImport.update({
  id: '/recommend',
  path: '/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderProjectIdRoute = BuilderProjectIdRouteImport.update({
  id: '/builder/$projectId',
  path: '/builder/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegalRoute,
} as any)
const LegalDocRoute = LegalDocRouteImport.update({
  id: '/$doc',
  path: '/$doc',
  getParentRoute: () => LegalRoute,
} as any)
const PreviewProjectIdRoute = PreviewProjectIdRouteImport.update({
  id: '/preview/$projectId',
  path: '/preview/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/legal': typeof LegalRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/recommend': typeof RecommendRoute
  '/start': typeof StartRoute
  '/api/health': typeof ApiHealthRoute
  '/builder/$projectId': typeof BuilderProjectIdRoute
  '/legal/$doc': typeof LegalDocRoute
  '/preview/$projectId': typeof PreviewProjectIdRoute
  '/legal/': typeof LegalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/recommend': typeof RecommendRoute
  '/start': typeof StartRoute
  '/api/health': typeof ApiHealthRoute
  '/builder/$projectId': typeof BuilderProjectIdRoute
  '/legal/$doc': typeof LegalDocRoute
  '/preview/$projectId': typeof PreviewProjectIdRoute
  '/legal': typeof LegalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/legal': typeof LegalRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/recommend': typeof RecommendRoute
  '/start': typeof StartRoute
  '/api/health': typeof ApiHealthRoute
  '/builder/$projectId': typeof BuilderProjectIdRoute
  '/legal/$doc': typeof LegalDocRoute
  '/preview/$projectId': typeof PreviewProjectIdRoute
  '/legal/': typeof LegalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/legal'
    | '/projects'
    | '/recommend'
    | '/start'
    | '/api/health'
    | '/builder/$projectId'
    | '/legal/$doc'
    | '/preview/$projectId'
    | '/legal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/recommend'
    | '/start'
    | '/api/health'
    | '/builder/$projectId'
    | '/legal/$doc'
    | '/preview/$projectId'
    | '/legal'
  id:
    | '__root__'
    | '/'
    | '/legal'
    | '/projects'
    | '/recommend'
    | '/start'
    | '/api/health'
    | '/builder/$projectId'
    | '/legal/$doc'
    | '/preview/$projectId'
    | '/legal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LegalRoute: typeof LegalRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
  RecommendRoute: typeof RecommendRoute
  StartRoute: typeof StartRoute
  ApiHealthRoute: typeof ApiHealthRoute
  BuilderProjectIdRoute: typeof BuilderProjectIdRoute
  PreviewProjectIdRoute: typeof PreviewProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommend': {
      id: '/recommend'
      path: '/recommend'
      fullPath: '/recommend'
      preLoaderRoute: typeof RecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/$projectId': {
      id: '/builder/$projectId'
      path: '/builder/$projectId'
      fullPath: '/builder/$projectId'
      preLoaderRoute: typeof BuilderProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/$doc': {
      id: '/legal/$doc'
      path: '/$doc'
      fullPath: '/legal/$doc'
      preLoaderRoute: typeof LegalDocRouteImport
      parentRoute: typeof LegalRoute
    }
    '/preview/$projectId': {
      id: '/preview/$projectId'
      path: '/preview/$projectId'
      fullPath: '/preview/$projectId'
      preLoaderRoute: typeof PreviewProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LegalRouteChildren {
  LegalDocRoute: typeof LegalDocRoute
  LegalIndexRoute: typeof LegalIndexRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalDocRoute: LegalDocRoute,
  LegalIndexRoute: LegalIndexRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LegalRoute: LegalRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
  RecommendRoute: RecommendRoute,
  StartRoute: StartRoute,
  ApiHealthRoute: ApiHealthRoute,
  BuilderProjectIdRoute: BuilderProjectIdRoute,
  PreviewProjectIdRoute: PreviewProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
